services:
  - type: web
    name: news-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: CURRENTS_API_KEY
        value: D_V4D-_qKDofwNTlk1W4hVkF1Gd-NwdMUtP7ySC2exFGbtm5
      - key: GNEWS_API_KEY
        value: 5a3e9cdd12d67717cfb6643d25ebaeb5
      - key: CACHE_TTL
        value: 300
      - key: API_KEY
        value: minha_chave_secreta_api
